name: tunduk
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  firebase_core: ^2.14.0
  flutter:
    sdk: flutter
  go_router: ^8.2.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.19
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/tunduk.png"

flutter_native_splash:
  color: "#1665C2"
